/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a92224f6-3bdb-423a-8a82-f76efd8f7605",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ibebQXOTp",
    "aws_user_pools_web_client_id": "7iartenj8027jg4rle4kb22494",
    "oauth": {},
    "aws_user_files_s3_bucket": "sketchin110800-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
